// Generated by CoffeeScript 1.12.4
var Kefir, KefirBus, KefirPoll;

Kefir = require('kefir');

KefirBus = require('kefir-bus');

module.exports = KefirPoll = function(t, pollFn, filterFn, readyFn) {
  var is_ready$, poll_status$, status$;
  status$ = KefirBus();
  is_ready$ = status$.filter(filterFn);
  poll_status$ = Kefir.interval(t).takeUntilBy(is_ready$).flatMap(pollFn);
  status$.plug(poll_status$);
  return is_ready$.take(1).flatMap(readyFn);
};
